### ISSUE TITLE
CMIP6_license  reworded

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#182] opened 2016-12-21 22:51 UTC
Here is the new wording for the license:

 "CMIP6 model data produced by <YourCentreName> is licensed under a Creative Commons Attribution \"[*] Share Alike\" 4.0 International License (http://creativecommons.org/licenses/by/4.0/). Use of the data should be acknowledged following guidelines found at https://pcmdi.llnl.gov/home/CMIP6/CitationRequirements6-0.html.  Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in data files)[and at <some URL maintained by modeling group>]. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law."

**Comment by durack1** [comment] 2016-12-22 00:15
@taylor13 this is a dupe of #133 so closing this and migrating the content across

**Closed by durack1** 2016-12-22 00:15 UTC
