### ISSUE TITLE
all CVs -- check for consistency with Martin and Denis

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#52] opened 2016-09-13 23:14 UTC
all CVs

Denis points out that the frequency, table_id, and realm CVs are not complete (or inconsistent with Martin's.  We need to check for correctness.

**Comment by durack1** [comment] 2016-09-13 23:15
@dnadeau4 @taylor13 please indicate what requires changing, or where this information can be obtained so we can maintain consistency

**Comment by durack1** [comment] 2016-09-28 21:07
@taylor13 @dnadeau4 @martinjuckes we are awaiting these details to be finalised the following outputs, see http://clipc-services.ceda.ac.uk/dreq/index.html
for e.g. [table_id/miptable](http://clipc-services.ceda.ac.uk/dreq/index/miptable.html)

We are going to have to double check realm, and possibly others..

**Comment by durack1** [comment] 2016-09-28 21:10
A duplicate of #51, closing

**Closed by durack1** 2016-09-28 21:10 UTC
