### ISSUE TITLE
experiment_id: rendering as html table

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#23] opened 2016-07-23 15:35 UTC
## Indicate the Controlled Vocabulary (CV) of interest: experiment_id (rendering as html table)

When we get to this, three changes are the priority:

1.  for column headings remove all "_", so that text can "wrap" and columns will be better spaced.

2.  Order of columns should be:

experiment id
activity id
experiment
tier
sub experiment id
sub experiment
parent experiment id
required model components
additional allowed model components
start year
end year
min number yrs per sim
parent activity id
description

3.  Can we make it possible to scroll through *all* rows of the table?  Now, you have to keep pressing "next" to get to the next group.  (At most you can scroll through 100 rows before pressing "next".)  If we can scroll through all rows, then a user could also, I think, print out the table with a single "print" click.

thanks,
Karl

On 7/20/16 12:54 PM, Charles Doutriaux wrote:
> Karl,
>
> For your column ordering issue, there are many ways to solve this:
>
> 1- using datables (for Denis):
>
> https://datatables.net/extensions/colreorder/
>
> 2- using collections.OrderedDict (for Paul)
>
> I would recommend 1 AND 2
>
> Paul's modifying the json will ensure that the tables will come out the way Karl wants them automatically
>
> Denis's using the plugin above will ensure that nobody will get more frustrated when Karl (or someone else) decide on another column ordring.
>
> C
>

**Comment by durack1** [comment] 2016-08-10 18:35
@dnadeau4 this is a dupe of #25 so closing this

**Closed by durack1** 2016-08-10 18:35 UTC
Labels: duplicate
