### ISSUE TITLE
inconsistency in table_id control vocabulary

### ISSUE THREAD

**Issue by dnadeau4** [WCRP-CMIP/CMIP6_CVs#128] opened 2016-11-03 21:24 UTC
Your CMIP6_table_id.json file has a table_id called "Aday",  it is defined as "day" only for the atmosphere table.  There is a SIday and a Oday.  See below the `current list` from Martins' database.  You might want to update this section.

https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_table_id.json#L7
http://clipc-services.ceda.ac.uk/dreq/index/miptable.html
```
01.beta.38
['3hr',
 '6hrLev',
 '6hrPlev',
 '6hrPlevpt',
 'Amon', # Following emMon (below) this should be camelCase AMon
 'AmonAdj',
 'LIfxant',
 'LIfxgre',
 'LImon',
 'LImonant',
 'LImongre',
 'LIyrant',
 'LIyrgre',
 'Lmon', #LMon
 'Oclim',
 'Oday',
 'Ofx',
 'Omon', #OMon
 'Oyr',
 'SIday',
 'SImon',
 'aerdaily', # This should be aerDay/aerday
 'aerfixed',
 'aerhourly', #aerhr to be consistent with 3hr, 6hrLev etc
 'aermonthly', #aerMon
 'cf3hr',
 'cfDay',
 'cfMon',
 'cfOff',
 'cfSites',
 'day', # This looks spurious to me, it should be Aday; Only fx and grids (bottom) are "realm-less"
 'em1hr',
 'em1hrclimmon',
 'em3hr',
 'em3hrpt',
 'emDay',
 'emDayZ',
 'emDaypt',
 'emFx',
 'emMon',
 'emMonZ',
 'emMonpt',
 'emSubhr',
 'emYr',
 'fx',
 'grids']
```

**Comment by durack1** [comment] 2016-11-03 21:28
@taylor13 this seems like an issue that should be fixed upstream (in Martin's stuff) so changing `day` -> `Aday`.. The `day` in his existing version appears arbitrary to me..

**Comment by durack1** [comment] 2016-11-03 21:32
@dnadeau4 where did you get the `table_id` values above? Could you edit the existing entry above with a sorted version of the same? It would make it easier to see what is missing/spurious between the different realms `atmos`, `ocean`, etc

**Comment by durack1** [comment] 2016-11-07 23:57
@dnadeau4 after talking with @taylor13 this is work in the queue to be resolved with @martinjuckes so that the final list can be set - once this is done we'll then bring our repo into sync with the final `table_id` values

**Comment by durack1** [comment] 2016-11-08 23:38
@dnadeau4 can you produce a list for the current 01.beta.39, is this identical to the list above? If yes, then I can temporally update the table_id entries to include the full list above, and this can be amended when the final list is ascertained in a couple of weeks

**Comment by durack1** [comment] 2016-12-12 19:11
@dnadeau4 Friday 9th December 2016 #179

Can you add `1hr` and `day` into the [CMIP6_table_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_table_id.json)

`cfmon` is also missing

**Comment by dnadeau4** [comment] 2016-12-13 01:32
I cannot release PrePARE it makes some of my tests fail.  I need to test with these tables.  This is a showstopper for me.

**Comment by durack1** [comment] 2016-12-14 05:23
The latest [01.beta.45](http://clipc-services.ceda.ac.uk/dreq/index.html) [mipTable](http://clipc-services.ceda.ac.uk/dreq/index/miptable.html) entries are as follows:
```
3hr: MIPtable::3hr
6hrLev: MIPtable::6hrLev
6hrPlev: MIPtable::6hrPlev
6hrPlevpt: MIPtable::6hrPlevpt
Amon: MIPtable::Amon
LIfxant: MIPtable::LIfxant
LIfxgre: MIPtable::LIfxgre
LImon: MIPtable::LImon
LImonant: MIPtable::LImonant
LImongre: MIPtable::LImongre
LIyrant: MIPtable::LIyrant
LIyrgre: MIPtable::LIyrgre
Lmon: MIPtable::Lmon
Oclim: MIPtable::Oclim
Oday: MIPtable::Oday
Odec: MIPtable::Odec
Ofx: MIPtable::Ofx
Omon: MIPtable::Omon
Oyr: MIPtable::Oyr
SIday: MIPtable::SIday
SImon: MIPtable::SImon
aerdaily: MIPtable::aerdaily
aerfixed: MIPtable::aerfixed
aerhourly: MIPtable::aerhourly
aermonthly: MIPtable::aermonthly
cf3hr: MIPtable::cf3hr
cfDay: MIPtable::cfDay
cfMon: MIPtable::cfMon
cfOff: MIPtable::cfOff
cfSites: MIPtable::cfSites
day: MIPtable::day
em1hr: MIPtable::em1hr
em1hrclimmon: MIPtable::em1hrclimmon
em3hr: MIPtable::em3hr
em3hrpt: MIPtable::em3hrpt
emDay: MIPtable::emDay
emDayZ: MIPtable::emDayZ
emDaypt: MIPtable::emDaypt
emFx: MIPtable::emFx
emMon: MIPtable::emMon
emMonZ: MIPtable::emMonZ
emMonpt: MIPtable::emMonpt
emSubhr: MIPtable::emSubhr
emYr: MIPtable::emYr
fx: MIPtable::fx
```

**Comment by dnadeau4** [comment] 2016-12-15 04:22
I will fix "cfMon", but it is still "day" in the file.

**Comment by durack1** [comment] 2016-12-15 04:32
I could update for the moment to `01.beta.45` while we sort everything else out.. would that get you moving?

**Comment by durack1** [comment] 2017-01-14 05:19
@dnadeau4 this is a dupe of #199, so closing

**Closed by durack1** 2017-01-14 05:19 UTC
Labels: More info required
