### ISSUE TITLE
table_id -- add frequency and realm (lists) to this CV?

### ISSUE THREAD

**Issue by taylor13** [WCRP-CMIP/CMIP6_CVs#51] opened 2016-09-13 23:12 UTC
table_id --  To enable QC checks be done on the frequency and realm attributes, I suggest we indicate the frequency and realm(s) that are included in each table in this CV.  (For many tables, there will be a single frequency and single realm.)  The syntax could be something like:

{
    "table_id":{
        "Amon":{
           "frequency":["mon", "monClim"],
           "realm":["atmos"]
         },
        "Omon":{
           "frequency":["mon"],
           "realm":["ocean"]
         },
.
.
.

**Comment by durack1** [comment] 2016-09-13 23:16
@taylor13 @dnadeau4 where is this information available

**Comment by durack1** [comment] 2016-09-28 21:09
@taylor13 following #52 (which is a duplicate and will be closed) I am appending the following information into this issue:
@taylor13 @dnadeau4 @martinjuckes we are awaiting these details to be finalised the following outputs, see http://clipc-services.ceda.ac.uk/dreq/index.html
for e.g. [table_id/miptable](http://clipc-services.ceda.ac.uk/dreq/index/miptable.html)

We are going to have to double check realm, and possibly others for consistency..

**Comment by durack1** [comment] 2016-09-29 16:38
@taylor13 copying information from #58 which is an effective duplicate of this issue (and will be closed):

table_id --
Martin's list of tables is still evolving. This CV will need to be updated in a few weeks.

**Comment by durack1** [comment] 2017-01-18 01:48
@taylor13 @dnadeau4 this is a dupe of #166, I have appended relevant information from this issue to #166 and am closing this

**Closed by durack1** 2017-01-18 01:48 UTC
Labels: More info required
