### ISSUE TITLE
frequency -- decadal or dec?

### ISSUE THREAD

**Issue by jonseddon** [WCRP-CMIP/CMIP6_CVs#338] opened 2017-06-01 09:35 UTC
In the frequency CV there is an entry for `decadal`. In the data request this is specified as `dec` e.g. http://clipc-services.ceda.ac.uk/dreq/u/47959ea8-bb0b-11e6-8316-5980f7b176d1.html. Is the data request or CV correct?

Thanks,

Jon

**Comment by durack1** [comment] 2017-06-01 14:55
@taylor13 @martinjuckes I believe we need to work out this kink and ensure that we're consistent across this repo and also the dataRequest

**Comment by taylor13** [comment] 2017-06-01 22:40
@eguil @martinjuckes @momipsl We need to confirm with es-doc, but our intent is to use "dec" for this frequency. The "dec" is consistent with the `Odec` table name from the Physics request in OMIP/Ocean variables: https://goo.gl/Rhrcwp
Need to correct this in:
CMIP6_frequency (this repo)
global attributes doc

**Comment by momipsl** [comment] 2017-06-02 11:20
Clearly this is a synonym use case.  It does not impact ES-DOC.

**Comment by taylor13** [comment] 2017-06-07 21:59
Thanks @jonseddon !  You've done enough work on this. Denis should be able to finish it up now.  I did find some ways to simplify the logic/coding a bit.   Although the test cases seem to work, I'm not quite sure the round-off will *always* work (and it's quite complicated).  Here is my suggested revision:

       /* -------------------------------------------------------------------- */
       /*      ok makes a comptime for start and end time                      */
       /* -------------------------------------------------------------------- */

	    i = cmor_vars[var_id].axes_ids[0];
	    j = cmor_axes[i].ref_table_id;
	    i = cmor_axes[i].ref_axis_id;

********* replace following segment

	    if( ( cmor_tables[j].axes[i].climatology == 1 )
		&& ( cmor_vars[var_id].first_bound != 1.e20 ) ) {
		cdRel2Comp( icalo, msg, cmor_vars[var_id].first_bound,
			    &starttime );
	    } else {
		cdRel2Comp( icalo, msg, cmor_vars[var_id].first_time,
			    &starttime );
	    }

	    if( ( cmor_tables[j].axes[i].climatology == 1 )
		&& ( cmor_vars[var_id].last_bound != 1.e20 ) ) {
		cdRel2Comp( icalo, msg, cmor_vars[var_id].last_bound,
			    &endtime );

	    
       /* -------------------------------------------------------------------- */
       /*      ok apparently we don't like the new time format                 */
       /*      if it's ending at midnight exactly so I'm removing              */
       /*      one second...                                                   */
       /* -------------------------------------------------------------------- */

		if( icalo == cdMixed ) {
		    cdCompAddMixed( endtime, -1. / 3600., &endtime );
		} else {
		    cdCompAdd( endtime, -1. / 3600., icalo, &endtime );
		}
	    } else {
		cdRel2Comp( icalo, msg, cmor_vars[var_id].last_time,
			    &endtime );
	    }

       /* -------------------------------------------------------------------- */
       /*      If times are less than half a second before midnight due to     */
       /*      floating point issues then add half a second to make sure       */
       /*      they indicate the next day as intended                          */
       /* -------------------------------------------------------------------- */

        if( starttime.hour > 23.99986 ) {
            if( icalo == cdMixed ) {
                cdCompAddMixed( starttime, 0.5 / 3600., &starttime );
            } else {
                cdCompAdd( starttime, 0.5 / 3600., icalo, &starttime );
            }
        }
        if( endtime.hour > 23.99986 ) {
            if( icalo == cdMixed ) {
                cdCompAddMixed( endtime, 0.5 / 3600., &endtime );
            } else {
                cdCompAdd( endtime, 0.5 / 3600., icalo, &endtime );
            }
        }

********* with

	    if( ( cmor_tables[j].axes[i].climatology == 1 ) {
		 cdRel2Comp( icalo, msg, cmor_vars[var_id].first_bound,
			    &starttime );
		 cdRel2Comp( icalo, msg, cmor_vars[var_id].last_bound,
			    &endtime );
	    } else {
		 cdRel2Comp( icalo, msg, cmor_vars[var_id].first_time,
			    &starttime );
		 cdRel2Comp( icalo, msg, cmor_vars[var_id].last_time,
			    &endtime );
	    }

       /* -------------------------------------------------------------------- */
       /*      We want start and end times that are greater than               */
       /*      x minutes 59.5 seconds to be set to x+1 minutes 0 seconds       */  
       /*      so add a half second so that when floats are converted to       */
       /*       integers, this will round to nearest second (we know that      */
       /*       the time coordinates are positive                              */
       /*
       /*    note that in the following, cdCompAdd expects the increment added */
       /*      to be expressed in units of hours                               */
       /* -------------------------------------------------------------------- */

	      
          if( icalo == cdMixed ) {
              cdCompAddMixed( starttime, 0.5 / 3600., &starttime );
              cdCompAddMixed( endtime, 0.5 / 3600., &endtime );

          } else {
              cdCompAdd( starttime, 0.5 / 3600., icalo, &starttime );
              cdCompAdd( endtime, 0.5 / 3600., icalo, &endtime );
          }

*********   end of replacement
      Note that in the first part above when climatology ==1, you might want to include the 
      logic to treat the case when the bounds are "missing".  In that case would it be 
      possible to set the starttime and endtime to 0000-00-00 00:00:00 ?  
      That would hopefully alert anyone looking at the file name that there was a problem.
      Note that in the second part above if CDMS were revised so that cdCompADD accepted 
      cdMixed type calendar, then we could eliminate the if/else construct.
      NOTE: BEFORE ADDING THIS LOGIC, CHECK WHETHER CMOR INITIALIZES BOUND 
            TO 1.e20 OR 1.d20      
      BOUNDS VARIABLES SHOULD BE DOUBLE PRECISION AND INITIALIZED TO 1.d20  
      Also, CMOR should check that the user has actually set the bounds, so checking
      again here shouldn’t be necessary.

     /* -------------------------------------------------------------------- */
     /*    need to figure out the frequency                                                         */
     /* -------------------------------------------------------------------- */

*********  modify as noted and move the following code segment to the beginning of the function

        int frequency_code;

**         delete following:

	    int nVarAxisID;
	    int nVarRefTable;
	    int nVarRefAxisID;

**         end deletion

	    char frequency[CMOR_MAX_STRING];
	    char start_string[CMOR_MAX_STRING];
	    char end_string[CMOR_MAX_STRING];

**          replace

	    float start_seconds, end_seconds, start_minutes, end_minutes;

**          with
        
          int start_seconds, end_seconds, start_minutes, end_minutes;

**            end replacement
*********  end of segment that should be moved to beginning 

********* delete following segment 

	    nVarAxisID = cmor_vars[var_id].axes_ids[0];
	    nVarRefTable = cmor_axes[nVarAxisID].ref_table_id;
	    nVarRefAxisID = cmor_axes[nVarAxisID].ref_axis_id;

*********  end of segment to be deleted 
	
        if( cmor_has_cur_dataset_attribute( GLOBAL_ATT_FREQUENCY ) == 0 ) {
        cmor_get_cur_dataset_attribute( GLOBAL_ATT_FREQUENCY, frequency );
        }
        
        if( strstr( frequency, "yr" ) != NULL ) {
        frequency_code = 1;
        } 
        else if( strstr( frequency, "dec" ) != NULL ) {
        frequency_code = 1;
        }

***********  insert 

        else if( strstr( frequency, “monClim) != NULL ) {
        frequency code = 6
        }

***********  end insertion

        else if( strstr( frequency, "mon" ) != NULL ) {
        frequency_code = 2;
        }
        else if( strstr( frequency, "day" ) != NULL ) {
        frequency_code = 3;
        }
        else if( strstr( frequency, "subhr" ) != NULL ) {
        frequency_code = 5;
        }
        else if( strstr( frequency, "hr" ) != NULL ) {
        frequency_code = 4;
        }
        else if( strstr( frequency, "fx" ) != NULL ) {
        frequency_code = 99;
        }
        else {
        frequency_code = 0;
        }
        
        switch ( frequency_code ) {
        case 1:
            /* frequency is yr, decadal */
            snprintf( start_string, CMOR_MAX_STRING, "%.4ld", starttime.year );
            snprintf( end_string, CMOR_MAX_STRING, "%.4ld", endtime.year );
            break;
        case 2:
            /* frequency is mon */
            snprintf( start_string, CMOR_MAX_STRING, "%.4ld%.2i", 
                    starttime.year, starttime.month );
            snprintf( end_string, CMOR_MAX_STRING, "%.4ld%.2i",
                    endtime.year, endtime.month );
            break;
        case 3:
            /* frequency is day */
            snprintf( start_string, CMOR_MAX_STRING, "%.4ld%.2i%.2i", 
                    starttime.year, starttime.month, starttime.day );
            snprintf( end_string, CMOR_MAX_STRING, "%.4ld%.2i%.2i",
                    endtime.year, endtime.month, endtime.day );
            break;
        case 4:
            /* frequency is 6hr, 3hr, 1hr */
            /* round to the nearest minute */
            start_minutes = round( ( starttime.hour -
                    ( int ) starttime.hour ) * 60. );
            end_minutes = round( ( endtime.hour -
                    ( int ) endtime.hour ) * 60. );
            snprintf( start_string, CMOR_MAX_STRING, "%.4ld%.2i%.2i%.2i%.2i",
                    starttime.year, starttime.month, starttime.day,

*********   replace

                    ( int ) starttime.hour, ( int ) start_minutes );

********* with  (start_minutes has been declared integer already)

                    ( int ) starttime.hour, start_minutes );

**********   end replacement

            snprintf( end_string, CMOR_MAX_STRING, "%.4ld%.2i%.2i%.2i%.2i",
                    endtime.year, endtime.month, endtime.day,

*********   replace

                    ( int ) endtime.hour, ( int ) end_minutes );

********* with  (start_minutes has been declared integer already)

                    ( int ) endtime.hour, end_minutes );

**********   end replacement

            break;
        case 5:
            /* frequency is subhr */
            /* round to the nearest second */

*********   replace (this modification should avoid any truncation error problems)

            start_seconds = round( ( starttime.hour -
                    ( int ) starttime.hour ) * 3600. );
            end_seconds = round( ( endtime.hour - 
                    ( int ) endtime.hour ) * 3600. );
            snprintf( start_string, CMOR_MAX_STRING, "%.4ld%.2i%.2i%.2i%.2i%.2i",
                    starttime.year, starttime.month, starttime.day,
                    ( int ) starttime.hour, ( int ) ( start_seconds / 60. ),
                    ( int ) fmod( start_seconds, 60. ) );
            snprintf( end_string, CMOR_MAX_STRING, "%.4ld%.2i%.2i%.2i%.2i%.2i",
                    endtime.year, endtime.month, endtime.day,
                    ( int ) endtime.hour, ( int ) ( end_seconds / 60. ),
                    ( int ) fmod( end_seconds, 60. ) );

********** with

            start_seconds = 
                   (int) (( starttime.hour - ( int ) starttime.hour ) * 3600 );
            end_seconds = 
                    (int)  (( endtime.hour - ( int ) endtime.hour ) * 3600 );
            snprintf( start_string, CMOR_MAX_STRING, "%.4ld%.2i%.2i%.2i%.2i%.2i",
                    starttime.year, starttime.month, starttime.day,
                    ( int ) starttime.hour, ( int ) ( start_seconds / 60 ),
                    ( start_seconds % 60 ) );
            snprintf( end_string, CMOR_MAX_STRING, "%.4ld%.2i%.2i%.2i%.2i%.2i",
                    endtime.year, endtime.month, endtime.day,
                    ( int ) endtime.hour, ( int ) ( end_seconds / 60 ),
                    ( end_seconds % 60 ) );


**********   end replacement

            break;

**********   insert

        case 6:
            /* frequency is monClim 
            /* add/subtract 1 hour (this is overkill, but safe)   
            /* to prevent truncation errors from possibly leading you to 
            /* the wrong month     
            /*
            /* note that cdCompAdd expects the increment added to be
            /*      expressed in units of hours 
 
            if( icalo == cdMixed ) {
                cdCompAddMixed( starttime, 1.0, &starttime );
                cdCompAddMixed( endtime, -1.0, &endtime );
            } else {
                cdCompAdd( starttime, 1.0, icalo, &starttime );
                cdCompAdd( endtime, -1.0, icalo, &endtime );
            }
            snprintf( start_string, CMOR_MAX_STRING, "%.4ld%.2i", 
                    starttime.year, starttime.month );
            snprintf( end_string, CMOR_MAX_STRING, "%.4ld%.2i",
                    endtime.year, endtime.month );
            break;

***********  end insertion
       Note that if cdtime were revised so that cdCompAdd could handle
       a “cdMixed” calendar, then the "if statement" above could be eliminated.

        case 99:
            /* frequency is fx */
            /* don't need to do anything, time string will ignored in next step */
            break;
        default:
		    snprintf( msg, CMOR_MAX_STRING,
			      "Cannot find frequency %s. Closing variable %s (table: %s)",
			      frequency, cmor_vars[var_id].id, cmor_tables[cmor_vars[var_id].
				          ref_table_id].szTable_id );
		    cmor_handle_error_var( msg, CMOR_CRITICAL, var_id );
		    cmor_pop_traceback(  );
		    return( 1 );
        }

***********   I haven't checked the rest of the code carefully, but one question:
                  Why is the warning on file size given at 4 gbytes rather than about 2 gbytes?

	if( cmor_vars[var_id].suffix_has_date == 1 ) {
    /* -------------------------------------------------------------------- */
    /*      all right we need to pop out the date part....                  */
    /* -------------------------------------------------------------------- */

	    n = strlen( cmor_vars[var_id].suffix );
	    i = 0;
	    while( cmor_vars[var_id].suffix[i] != '_' )
		i++;
	    i++;
	    while( ( cmor_vars[var_id].suffix[i] != '_' ) && i < n )
		i++;
    /* -------------------------------------------------------------------- */
    /*      ok now we have the length of dates                              */
    /*      at this point we are either at the                              */
    /*      _clim the actual _suffix or the end (==nosuffix)                */
    /*      checking if _clim needs to be added                             */
    /* -------------------------------------------------------------------- */
	    if( cmor_tables
		[cmor_axes[cmor_vars[var_id].axes_ids[i]].
		 ref_table_id].axes[cmor_axes[cmor_vars[var_id].
					      axes_ids[0]].
				    ref_axis_id].climatology == 1 ) {
		i += 5;
	    }
	    strcpy( msg, "" );
	    for( j = i; j < n; j++ ) {
		msg[j - i] = cmor_vars[var_id].suffix[i];
		msg[j - i + 1] = '\0';
	    }
	} else {
	    strncpy( msg, cmor_vars[var_id].suffix, CMOR_MAX_STRING );
	}

	if( strlen( msg ) > 0 ) {
	    strncat( outname, "_", CMOR_MAX_STRING - strlen( outname ) );
	    strncat( outname, msg, CMOR_MAX_STRING - strlen( outname ) );
	}
	strncat( outname, ".nc", CMOR_MAX_STRING - strlen( outname ) );


    /* -------------------------------------------------------------------- */
    /*      ok now we can actually move the file                            */
    /*      here we need to make sure we are not in preserve mode!          */
    /* -------------------------------------------------------------------- */
	if( ( CMOR_NETCDF_MODE == CMOR_PRESERVE_4 )
	    || ( CMOR_NETCDF_MODE == CMOR_PRESERVE_3 ) ) {
	    FILE *fperr;

    /* -------------------------------------------------------------------- */
    /*      ok first let's check if the file does exists or not             */
    /* -------------------------------------------------------------------- */
            fperr = NULL;
            fperr = fopen(outname, "r");
            if (fperr != NULL) {
                sprintf(msg, "%s.copy", outname);
                if (rename(cmor_vars[var_id].current_path, msg) == 0) {
                    snprintf(msg, CMOR_MAX_STRING,
                            "Output file ( %s ) already exists,\n! "
                                    "remove file or use CMOR_REPLACE or\n! "
                                    "CMOR_APPEND for CMOR_NETCDF_MODE value\n! "
                                    "in cmor_setup for convenience the file\n! "
                                    "you were trying to write has been saved\n! "
                                    "at: %s.copy", outname, outname);
                } else {
                    snprintf(msg, CMOR_MAX_STRING,
                            "Output file ( %s ) already exists,\n! "
                                    "remove file or use CMOR_REPLACE or\n! "
                                    "CMOR_APPEND for CMOR_NETCDF_MODE value in\n! "
                                    "cmor_setup.", outname);
                }
                ierr = fclose(fperr);
                fperr=NULL;
                cmor_handle_error_var(msg, CMOR_CRITICAL, var_id);
            }
        }
	ierr = rename( cmor_vars[var_id].current_path, outname );
	if( ierr != 0 ) {
	    snprintf( msg, CMOR_MAX_STRING,
		      "could not rename temporary file: %s to final file\n"
	              "name: %s",
		      cmor_vars[var_id].current_path, outname );
	     cmor_handle_error_var( msg, CMOR_CRITICAL, var_id );
	}
	if( file_name != NULL ) {
	    strncpy( file_name, outname, CMOR_MAX_STRING );
	}
        strncpy( cmor_current_dataset.finalfilename, outname,
                CMOR_MAX_STRING);

    /* -------------------------------------------------------------------- */
    /*      At this point we need to check the file's size                  */
    /*      and issue a warning if greater than 4Gb                         */
    /* -------------------------------------------------------------------- */
	stat( outname, &buf );
	sz = buf.st_size;
	if( sz > maxsz ) {
	    sprintf( msg,
		     "Closing file: %s size is greater than 4Gb, while\n! "
	             "this is acceptable \n! ",
		     outname );
	    cmor_handle_error_var( msg, CMOR_WARNING, var_id );
	}

	if( preserve != NULL ) {
	    cmor_vars[var_id].initialized = -1;
	    cmor_vars[var_id].ntimes_written = 0;
	    cmor_vars[var_id].time_nc_id = -999;
	    cmor_vars[var_id].time_bnds_nc_id = -999;
	    for( i = 0; i < 10; i++ ) {
		cmor_vars[var_id].ntimes_written_coords[i] = -1;
		cmor_vars[var_id].ntimes_written_associated[i] = 0;
		cmor_vars[var_id].associated_ids[i] = -1;
		cmor_vars[var_id].nc_var_id = -999;
	    }
	    for( i = 0; i < cmor_vars[var_id].nattributes; i++ ) {
		if( strcmp( cmor_vars[var_id].attributes[i],
		        "cell_methods" ) == 0 ) {
		    cmor_set_variable_attribute_internal( var_id,
		            "cell_methods",
		            'c',
		            cmor_tables[cmor_vars[var_id].ref_table_id].
		            vars[cmor_vars[var_id].ref_var_id].cell_methods );
		}
	    }
	} else {
	    cmor_reset_variable( var_id );
	    cmor_vars[var_id].closed = 1;
	}
    }
    cleanup_varid = -1;
    cmor_pop_traceback(  );
    return( 0 );
}

**Comment by jonseddon** [comment] 2017-06-08 13:25
@taylor13 @dnadeau4 Thanks for finishing off! Could you let me know when the changes are merged into master? Thanks! Jon

**Comment by dnadeau4** [comment] 2017-06-13 18:40
@jonseddon I was on travel in DC last week.  I cloned and merged your branch and need to rerun tests.  I should merge today.

**Comment by taylor13** [comment] 2017-06-13 18:43
@dnadeau4 You also need to make the code changes noted in https://github.com/WCRP-CMIP/CMIP6_CVs/issues/338#issuecomment-306937576

**Closed** 2017-06-14 20:37 UTC
