### ISSUE TITLE
License change for UofT-CCSM4

### ISSUE THREAD

**Issue by dchandan** [WCRP-CMIP/CMIP6_CVs#1086] opened 2022-06-08 23:36 UTC
I confirm that UofT-CCSM4 license can be updated to CC BY 4.0.

**Comment by durack1** [comment] 2022-06-08 23:46
Thanks @dchandan! We had actually identified [`UofT-CCSM4` as a model that had no data available through the CMIP6 ESGF project](https://esgf-node.llnl.gov/search/cmip6/?source_id=UofT-CCSM4), and so were querying whether deregistration was a suitable path forward?

**Comment by dchandan** [comment] 2022-06-08 23:57
Hi Paul, yes we are only contributing to PMIP4 and not to CMIP6 itself. What should we do?

**Comment by durack1** [comment] 2022-06-09 00:01
@dchandan `PMIP4` (or [`PMIP` under the CMIP6 project](https://esgf-node.llnl.gov/search/cmip6/?activity_id=PMIP)) is a valid activity with 6 contributing experiments. Ideally, getting your data published on ESGF so it's part of the official archive would be the preferred path forward

**Comment by durack1** [comment] 2022-06-09 04:34
This open issue is now a dupe of the unanswered questions in #512 (will close)

**Comment by durack1** [comment] 2022-06-14 16:53
@dchandan I was trying to ascertain where `UofT-CCSM4` has been used in CMIP6/AR6, and it seems your entry is omitted in the CMIP6 data listed used in the AR6 report - see [AR6 WG1 AnnexII](https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_AnnexII.pdf#Page=15). Is this an error in the AR6 report?

**Comment by durack1** [comment] 2022-06-28 17:22
This will also lead to deregistration of institution_id = UofT

**Closed** 2022-07-01 19:12 UTC

**Comment by durack1** [comment] 2022-07-01 19:14
@dchandan that change in now in place, and all HTML files updated
