### ISSUE TITLE
source_id registration of CanESM5-1

### ISSUE THREAD

**Issue by slavakharin** [WCRP-CMIP/CMIP6_CVs#1148] opened 2022-09-07 22:20 UTC
```
           "CanESM5-1":{
                "activity_participation":[
                    "C4MIP",
                    "CDRMIP",
                    "CFMIP",
                    "CMIP",
                    "CORDEX",
                    "DAMIP",
                    "DCPP",
                    "DynVarMIP",
                    "FAFMIP",
                    "GMMIP",
                    "GeoMIP",
                    "ISMIP6",
                    "LS3MIP",
                    "LUMIP",
                    "OMIP",
                    "PAMIP",
                    "RFMIP",
                    "SIMIP",
                    "ScenarioMIP",
                    "VIACSAB",
                    "VolMIP"
                ],
                "cohort":[
                    "Registered"
                ],
                "institution_id":[
                    "CCCma"
                ],
                "source_id":"CanESM5-1",
                "source":"CanESM5.1 (2022): \naerosol: interactive\natmos: CanAM5.1 (T63L49 native atmosphere, T63 Linear Gaussian Grid; 128 x 64 longitude/latitude; 49 levels; top level 1 hPa)\natmosChem: specified oxidants for aerosols\nland: CLASS3.6/CTEM1.2\nlandIce: specified ice sheets\nocean: NEMO3.4.1 (ORCA1 tripolar grid, 1 deg with refinement to 1/3 deg within 20 degrees of the equator; 361 x 290 longitude/latitude; 45 vertical levels; top grid cell 0-6.19 m)\nocnBgchem: Canadian Model of Ocean Carbon (CMOC); NPZD ecosystem with OMIP prescribed carbonate chemistry\nseaIce: LIM2"
            },
```

**Comment by durack1** [comment] 2022-09-09 05:16
@slavakharin can you reproduce all the fields as per below please - the above is the truncated format that is found in the [`cmip6-cmor-tables/Tables/MIP6_CV.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L968-L1008)

https://github.com/WCRP-CMIP/CMIP6_CVs/blob/9c0223b0262b1f233265d7c70b112ec8979088dc/CMIP6_source_id.json#L2069-L2145

It looks to me like we also need to clean up your garbled email address, `"@canada.ca <- ec.cccma.info-info.ccmac.ec", ` looks like something went wrong here

**Comment by durack1** [comment] 2022-09-16 01:08
@slavakharin just circling around on this request, are you able to provide the required info?

**Comment by durack1** [comment] 2022-09-27 21:00
@jamesAnstey welcome to the repo, just looping you in

**Comment by JamesAnstey** [comment] 2022-09-27 21:28
@durack1 the contact email in our CMIP6 netcdf metadata should be
```
contact = "ec.cccma.info-info.ccmac.ec@canada.ca" 
```
It looks like the garbled version has just rearranged the bits of the address and other models seem to have the same problem. Maybe an issue with the script that ingests this info from the netcdf files?

**Comment by durack1** [comment] 2022-09-27 21:42
@JamesAnstey nope, the email is intentionally garbled with `<-` and rearranging, so that bots have a hard time trying to stick it back together - we've been masking all email addresses or obscuring them to limit spam.

As an aside, that is one of the most complicated email addresses that I think I have ever seen, I was convinced something had gone wrong in the data writing

**Comment by JamesAnstey** [comment] 2022-09-27 22:15
@durack1 ah sorry I misunderstood! Yes, a long address is not uncommon for official Canadian government addresses, which combine both English and French versions.

**Comment by durack1** [comment] 2022-09-27 22:22
@JamesAnstey getting back to the focus of this issue, @slavakharin wants to register a new model version, but we don't have enough information provided to do so, could you circle around and provide all the require details please? The required template is linked in https://github.com/WCRP-CMIP/CMIP6_CVs/issues/1148#issuecomment-1241508461 above

**Comment by slavakharin** [comment] 2022-09-27 22:55
@durack1 sorry Paul for being so slow. Here is a revised version
```
"CanESM5-1":{
            "activity_participation":[
                "C4MIP",
                "CDRMIP",
                "CFMIP",
                "CMIP",
                "CORDEX",
                "DAMIP",
                "DCPP",
                "DynVarMIP",
                "FAFMIP",
                "GMMIP",
                "GeoMIP",
                "ISMIP6",
                "LS3MIP",
                "LUMIP",
                "OMIP",
                "PAMIP",
                "RFMIP",
                "SIMIP",
                "ScenarioMIP",
                "VIACSAB",
                "VolMIP"
            ],
            "cohort":[
                "Published"
            ],
            "institution_id":[
                "CCCma"
            ],
            "label":"CanESM5.1",
            "label_extended":"CanESM5.1",
            "license_info":{
                "exceptions_contact":"@canada.ca <- ec.cccma.info-info.ccmac.ec",
                "history":"2019-03-06: initially published under CC BY-SA 4.0",
                "id":"CC BY-SA 4.0",
                "license":"Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0; https://creativecommons.org/licenses/by-sa/4.0/)",
                "source_specific_info":"",
                "url":"https://creativecommons.org/licenses/by-sa/4.0/"
            },
            "model_component":{
                "aerosol":{
                    "description":"interactive",
                    "native_nominal_resolution":"500 km"
                },
                "atmos":{
                    "description":"CanAM5 (T63L49 native atmosphere, T63 Linear Gaussian Grid; 128 x 64 longitude/latitude; 49 levels; top level 1 hPa)",
                    "native_nominal_resolution":"500 km"
                },
                "atmosChem":{
                    "description":"specified oxidants for aerosols",
                    "native_nominal_resolution":"500 km"
                },
                "land":{
                    "description":"CLASS3.6/CTEM1.2",
                    "native_nominal_resolution":"500 km"
                },
                "landIce":{
                    "description":"specified ice sheets",
                    "native_nominal_resolution":"500 km"
                },
                "ocean":{
                    "description":"NEMO3.4.1 (ORCA1 tripolar grid, 1 deg with refinement to 1/3 deg within 20 degrees of the equator; 361 x 290 longitude/latitude; 45 vertical levels; top grid cell 0-6.19 m)",
                    "native_nominal_resolution":"100 km"
                },
                "ocnBgchem":{
                    "description":"Canadian Model of Ocean Carbon (CMOC); NPZD ecosystem with OMIP prescribed carbonate chemistry",
                    "native_nominal_resolution":"100 km"
                },
                "seaIce":{
                    "description":"LIM2",
                    "native_nominal_resolution":"100 km"
                }
            },
            "release_year":"2022",
            "source_id":"CanESM5-1"
        },
```

Most fields are the same except for model version CanESM5 -> CanESM5.1. Presumably I can use the period "." in the `label` and `label_extended` tags, but the period is replaced by the dash in the `source_id`. Is this correct?

Also the release year is replaced with 2022.

I am not sure about the `Cohort` tag. It says "published" for the CMIP6 CanESM5 model. What should it be for the newer version CanESM5.1?

The `license_info` tag needs revision, probably just removing the history infor.

**Comment by JamesAnstey** [comment] 2022-09-27 23:15
@durack1 @slavakharin I think the license can be changed to 
```
     "license_info":{ 
         "exceptions_contact":"ec.cccma.info-info.ccmac.ec@canada.ca", 
         "history":"published under CC BY 4.0", 
         "id":"CC BY 4.0", 
         "license":"Creative Commons Attribution 4.0 International (CC BY 4.0; https://creativecommons.org/licenses/by/4.0/)", 
         "source_specific_info":"", 
         "url":"https://creativecommons.org/licenses/by/4.0/" 
     }, 
```
since that's the new CMIP recommendation and our CMIP6 CanESM5 output now uses this license.

Also under "atmos" in "model_component", should it be "CanAM5.1" instead of "CanAM5"? That's what was originally specified in the abridged version, but @slavakharin can you confirm?

**Comment by slavakharin** [comment] 2022-09-27 23:18
@durack1 The license info looks good to me. Good eye for CanAM5.1, thank you! Yes it should be CanAM5.1!

**Comment by durack1** [comment] 2022-09-27 23:20
Gents, it appears that data is not yet (openly) published - https://esgf-node.llnl.gov/search/cmip6/?source_id=CanESM5-1 if so, I suggest we catch the license, relaxing this to `CC BY 4.0` within files if possible, which means the license history will be `"2022-09-27: initially published under CC BY 4.0"` with the appropriate date of publication replacing the `2022-09-27` (today's date)

**Comment by slavakharin** [comment] 2022-09-27 23:28
@JamesAnstey @durack1 We still need to properly CMORize the CanESM5.1 files before publishing on ESGF. @JamesAnstey  would probably know better how to get the updated license information into the cmorized files.

**Comment by durack1** [comment] 2022-09-27 23:37
Note that the revised mailing list address `@ec.gc.ca <- f.cccma.info-info.ccmac.f` will need to be used - and written as a replacement in files, if they haven't already been written

**Comment by JamesAnstey** [comment] 2022-09-27 23:55
@durack1 correct, CanESM5.1 data isn't yet published on ESGF. Do you mean that the license info in the [CV repo](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json) will be updated when we first publish CanESM5.1 data to ESGF? That sounds fine to me.

Our existing CMIP6 output published on ESGF has this for "license" in the netcdf metadata:

"CMIP6 model data produced by The Government of Canada (Canadian Centre for Climate Modelling and Analysis, Environment and Climate Change Canada) is licensed under a Creative Commons Attribution ShareAlike 4.0 International License (https://creativecommons.org/licenses). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file) and at https:///pcmdi.llnl.gov/. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law." ;

When we publish new data we can change "Attribution ShareAlike 4.0 International" to "Attribution 4.0 International" and also update the metadata "contact" field (email address).

**Comment by durack1** [comment] 2022-09-28 00:06
@JamesAnstey that's right. We have no expectation that folks will republish the ~13 PB of data that has already been published since ~2018, so rather we are updating this information for each model on the webpage [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) which effectively replaces the in-file license info.

My hope, was that data generated AFTER the relaxation of the existing data is made, would be updated to reflect the new relaxed `CC BY 4.0` in the files as well as the webpage

**Comment by durack1** [comment] 2022-09-28 05:22
@JamesAnstey if it makes your data writing/publishing pipeline easier, we could publish this new registration with a `cohort = Registered` status, and update this once the data is live, and we have a publication/version_id date

**Comment by JamesAnstey** [comment] 2022-09-29 21:44
@durack1 Yes, I was referring to any future data publishing, not republishing of any existing CMIP6 CanESM output. I just meant that new datasets can contain the updated license and contact email, and this is straightforward in our publishing pipeline. For the CV update (source_id registration) we're discussing here, using `cohort = Registered` for now sounds fine to me.

**Comment by durack1** [comment] 2022-09-29 23:40
@JamesAnstey the new model is now registered, but we have no license information, as this requires the first date of data publication on ESGF (the v20220929 identifier, e.g. today). I will keep this issue open until you have data published.

Please take a peek at the published info [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) and let me know of any corrections

**Comment by taylor13** [comment] 2022-12-07 18:26
@JamesAnstey Thanks for the update.  Paul is in Australia for the holiday, so won't be able to update things until January.

**Comment by durack1** [comment] 2023-01-24 22:46
@JamesAnstey this is great news! I just went to poll the archive to extract the version number (so the license info can be completed) and it seems your CCCma node is down - can you ping me when this is live, and I'll finalize the license info and close the issue!

**Comment by JamesAnstey** [comment] 2023-01-25 17:57
@durack1 Ok it should be live now - I just tested by downloading a dataset from it. Can you try it now?

**Comment by durack1** [comment] 2023-02-09 23:50
@JamesAnstey apologies circling around on this now. Your earliest version appears to be `20190429` which is WAAAY earlier than I was expecting - the [`source_id` registration notes the model notes a `release_year = 2022`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json#L2219)

**Comment by JamesAnstey** [comment] 2023-02-10 17:44
@durack1 We use `v20190429` as the default version identifier for our CMIP6 output, this date being roughly when we first started publishing CanESM5 output on ESGF. If we have to retract and republish data then we assign it a new version identifier that gives the republication date. Is this usage of the version identifier consistent with ESGF/CMIP expectations? We could reconsider if necessary, but it likely would require some discussion in the group re. where setting the version identifier is baked into our CMORization pipeline. 

I guess it would make more sense if the default version corresponded to the initial publication date for a given `source_id`, which would make it `v2022[something]` for `CanESM5-1`. Is that what's ESGF/CMIP expects? I think we do want to keep the policy of having one default identifier for a model's output, because this makes it straightforward to identify data that was retracted and republished.

**Comment by taylor13** [comment] 2023-02-10 18:39
The idea was that you would record in source_id CV a date indicating when the model version was released (used in a simulation that might be cited in a publication).   The version number should be a date on or before (but usually near) which a dataset is published.  If data is flawed and replaced with a new version, the new version would be a date after the original dataset version date and should be near the new date of publication (and never after it).  Hope this helps.

**Comment by durack1** [comment] 2023-02-10 18:47
@JamesAnstey no need to retract, but FYI, the version identifier is meant to reflect the approximate date that the data was written (and then hopefully soon thereafter) published on ESGF - using the format `vYYYYMMDD` (see p 17 in [CMIP6 Global Attributes, DRS, Filenames, Directory Structure, and CV’s](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit). This attribute is written at runtime in the demo templates we have for CMOR, assuming the current time. You have hard-coded this somewhere, which subverts the auto-update.

> I guess it would make more sense if the default version corresponded to the initial publication date for a given `source_id`, which would make it `v2022[something]` for `CanESM5-1`. Is that what's ESGF/CMIP expects? I think we do want to keep the policy of having one default identifier for a model's output, because this makes it straightforward to identify data that was retracted and republished.

Exactly. This means that it becomes far easier for an updated dataset to be easily identified and then replicated, replacing the previous version/dated data. Obviously the `tracking_id` and other file metadata attributes will be updated, but the DRS/Directory version info is a key way to easily manage the very large data holdings, if it's done correctly.

It would be great from now on, if you can remove this hard-coding so that this same wrinkle doesn't continue.

We have a single example of this occurring the past (see [here](https://github.com/WCRP-CMIP/CMIP6_CVs/issues/1076#issuecomment-1233342460)), which breaks the linkage with the license date and the DRS/ESGF version date (your `v20190429`). As this was published in `202212xx` what should that date be?

For a [single dataset](https://esgf-node.llnl.gov/search/cmip6/?source_id=CanESM5-1&experiment_id=piControl&table_id=Amon&variable_id=rlds&variant_label=r1i1p1f1) (example below) this would be `v20221202`:
```
id = CMIP6.CMIP.CCCma.CanESM5-1.piControl.r1i1p1f1.Amon.rlds.gn.v20190429|crd-esgf-drc.ec.gc.ca
version = 20190429
_timestamp = 2022-12-02T19:01:59.903Z 
```
And following the previous example, I'll use the publication date in the license history: `2022-12-02: initially published under CC BY 4.0`, make sense?

**Comment by durack1** [comment] 2023-02-10 18:49
So sorry, to clarify. What is the earliest publication date for the CanESM5-1 datasets, the initial publication date?

**Comment by taylor13** [comment] 2023-02-10 19:03
Just to note a further detail.  If your processing spans more than one day, then you might have to override the default date supplied by CMOR (if that's what you're using) because files written before midnight would have a different date from files written after midnight.  [I think what I've said here is correct, but not absolutely sure.  Perhaps someone can confirm.]  We should probably have CMOR create a time-step when it is initialized and not recreate the time-stamp at the point it is writing a file.  That would ensure (under at least some operating procedures) that all files in a single dataset were assigned the same version number.

**Comment by JamesAnstey** [comment] 2023-02-10 19:50
I think we'd prefer to keep using one default version identifier for a given model version, which only gets changed for datasets that are retracted & republished. This was our interpretation of "indicating a representative date for the version" on p. 17 of the [DRS](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit). Otherwise the original published output for a given model would have version identifiers covering a range of dates that depend on when we happened to do each model run and write its output. E.g. for a historical large ensemble, different realizations could end up with different version identifiers.

It sounds like this usage will be consistent with ESGF expectation for license info and replication, provided that a "representative" version identifier for the model version is not a date that's very out-of-date (correct me if I've misunderstood). So I'll look into us changing this - i.e., updating from our use of `v20190429` - for future publications; it requires some technical checking and discussion with others in our group.

I checked the `_timestamp` of published data and yes it looks like 2022-12-02 (2 Dec 2022) is the earliest publication date for `CanESM5-1` data. So using `2022-12-02: initially published under CC BY 4.0` makes sense to me.

**Comment by taylor13** [comment] 2023-02-10 20:01
There may be some difference of opinion about this, but I think it's o.k. to have the *dataset* version number be any date on or before the date the data are written and after the release date of the model (which is recorded in the source_id).  If you adopt this approach, you *must be sure* to remember to instruct CMOR to use a date for any replacement datasets that comes after the date of the originally published datasets.  

I think it's perfectly o.k. if the release date for a model is long ago.  You might want to do an AMIP run with a very old model of yours, and in that case the model should be registered (in source_id CV) with the date the model was released (long ago).   The release date of the model doesn't have to be near the run date, the CMORizing date, or the ESGF publishing date.

**Closed** 2023-02-22 05:19 UTC
Labels: Awaiting info, Awaiting data publication

**Comment by durack1** [comment] 2023-02-22 06:07
@JamesAnstey apologies for the delay on this one. That update is now in place, so please take a peek at [CMIP6_source_id_licenses.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id_licenses.html) and let me know if there are any remaining inconsistencies
