### ISSUE TITLE
institution_id -- add official insititute URL?

### ISSUE THREAD

**Issue by davidhassell** [WCRP-CMIP/CMIP6_CVs#705] opened 2019-05-22 14:40 UTC
Hello,

ES-DOC would like to display an official URL for an institute on the further_info_url pages, e.g.   https://furtherinfo.es-doc.org/CMIP6.MOHC.HadGEM3-GC31-HM.abrupt-4xCO2.none.r1i1p1f1 These pages currently use a URL that seems sensible to us, but may not be what the modelling group would want. Note that this institute URL is a general one, and so is distinct from  the so-called  "further further_info_url", which relates to a CMIP6-specific page, which will be collected independently by ES-DOC.

We wondering if a) CMIP already has such general URLs and b) if not, would CMIP like to collect them and store them in this CV?

If the answer to both of these questions is "no", then there is no problem, as ES-DOC will simply  collect the information from the ES-DOC liaison at each institute, but if "yes" to either of them, we can of could harvest the information from the CMIP6 CV.

Many thanks,
David Hassell

**Comment by taylor13** [comment] 2019-05-22 15:20
Hi David,

We could add it to CMIP6_institution_id.json, but that would require modifying that file from being a simple dictionary.  Also, I would say the url might be somewhat less permanent than the full institution name and address, so the CV's would need to evolve (which is not a good thing).  So, currently I think the answer is "no" to both questions and you should feel free to obtain the information from the modeling groups for es-doc.

Any thoughts, Paul?

Karl

**Comment by durack1** [comment] 2019-05-22 16:00
@davidhassell thanks for this, it's on the to-do list and this issue is a dupe of #379

**Comment by davidhassell** [comment] 2019-05-22 16:09
Hi Karl and Paul,

I was just writing back to say "ES-DOC will get these, no need to change on the CMIP6 side" when I saw Paul's reply. I guess I should have known about #379, as it came from es-doc ...

So does that mean the answer is in fact "yes" to both questions (I couldn't see a PR relating to #379)?

David

**Comment by durack1** [comment] 2019-05-22 16:32
This is a dupe of #379 

@davidhassell we needed to reconfigure a number of things on this side at the same time that the CV update is undertaken, as there was no immediate need I had delayed this, but it seems this is now an ES-DOC requirement (correct?) which will pull it back up the priority list

**Comment by davidhassell** [comment] 2019-05-22 17:10
Hi Paul,

It is an ES-DOC requirement, but only one which we don't need until "later in the year", when we are scheduled to go back to the ES-DOC liaisons to gather Experiment documentation. So - needed, but not desperately urgent.

**Comment by durack1** [comment] 2019-05-22 18:11
@davidhassell "later this year" was about the timeline that I was working to implement the change - just so we're aligning calendars, what month/when is "later this year", I was thinking post-June..

**Comment by davidhassell** [comment] 2019-05-23 06:47
@durack1 Yes, most definitely post-June

**Comment by durack1** [comment] 2019-05-23 15:57
@davidhassell I will close this issue as a dupe, and we can continue discussions in #379 as that's where we all seem to be coalescing

**Closed by durack1** 2019-05-23 15:57 UTC
Labels: duplicate
