### ISSUE TITLE
missing tables 

### ISSUE THREAD

**Issue by dnadeau4** [WCRP-CMIP/CMIP6_CVs#179] opened 2016-12-09 19:52 UTC
Can you add `1hr` and `day` into the [CMIP6_table_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_table_id.json)

**Comment by dnadeau4** [comment] 2016-12-09 20:22
`cfmon` is also missing

**Comment by durack1** [comment] 2016-12-12 19:11
@dnadeau4 this is a dupe of #128, I have copied the details above across and am closing this issue

**Closed by durack1** 2016-12-12 19:11 UTC
