### ISSUE TITLE
table_id augment format with identifiers

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_CVs#166] opened 2016-11-30 14:01 UTC
```
From: SENESI Stéphane
Date: Wednesday, November 30, 2016 at 5:57 AM
To: Paul Durack, "Taylor, Karl E.", martin juckes
Cc: Marie-Pierre Moine, Arnaud Caubel
Subject: Proposal for an additional table in CMIP6 CV or CMIP6 DR : table2freq

Paul, Karl, Martin

A table is missing in CMIP6 CV (or in the DR), which would give the frequency corresponding to a table. This is useful when computing the DRS filename for a given table.
Would you agree to embark it, either in the CV or in the DR ?

Below is the content for a prototype, which additionally provides the frequency using XIos syntax for time elements

Best regards

S.

""" 
    Provide frequencies for a table name - Both in XIOS syntax and in CMIP6_CV 
    
    Rationale: Because CMIP6_CV does not (yet) provide the correspondance between a table name 
    and the corresponding frequency (albeit this is instrumental in DRS), and because 
    we need to translate anyway to XIOS syntax
"""

table2freq={
    "3hr"  : ("3h","3hr"),
    "3hrpt": ("3h","3hr"),
    "6hr"  : ("6h","6hr"),
    "6hrpt": ("6h","6hr"),
    "6hrPlev": ("6h","6hr"),
    "6hrPlevpt": ("6h","6hr"),
    "day"  : ("1d","day"),
    "Aday" : ("1d","day"),
    "Amon" : ("1mo","mon"),
    "AmonAdj": ("TBD","TBD"),
    "LImon": ("1mo","mon"),
    "Lmon" : ("1mo","mon"),
    "OImon": ("1mo","mon"),
    "Oclim": ("once","monClim"),
    "Oday" : ("1d","day"),
    "Odec" : ("1y","yr"),
    "Omon" : ("1mo","mon"),
    "Oyr"  : ("1y","yr"),
    "aero" : ("TBD","TBD"),
    "cfMon": ("1mo","mon"),
    "cfDay": ("1d","day"),
    "cfOff": ("TBD","TBD"),
    "cfSites": ("TBD","TBD"),
    "fx"   : ("once","fx"),
    "Ofx"  : ("once","fx"),
    "emYr" : ("1y","yr"),
    "emMon": ("1mo","mon"),
    "emMonZ": ("1mo","mon"),
    "emMonclim": ("1mo","mon"),
    "SImon" : ("1mo","mon"),
    "SIday" : ("1d","day"),
    "SPECS_OImon" : ("1mo","mon"),
    "SPECS_Omon" :("1mo","mon"),
}

-- 
----- Météo-France -----
SENESI STEPHANE
CNRM/GMGEC/ASTER 
stephane.senesi@
Fixe : +33 561079
```
Ref: http://clipc-services.ceda.ac.uk/dreq/index/miptable.html - I note the values above and those at the URL (left) are not consistent

Linked to #128

**Comment by senesis** [comment] 2016-11-30 14:33
If the inconsistency is only on the mode 'some table labels from URL are missing in the proposed table', I agree; It was not my goal to be comprehensive, but rather to pinpoint a missing piece in the CV

**Comment by durack1** [comment] 2016-11-30 14:37
@senesis this "inconsistency" noted below I am not certain of the source, there should be an `Odec` MIPTable, but at least in the version of the URL linked above it's not yet there (for me at least).. We had flagged this as an issue that needs to be investigated earlier in the month, see #128

**Comment by taylor13** [comment] 2016-11-30 16:53
@senesis @durack1 I think adding the information in this way is a good idea.   Some of the tables may be concatenated into a single table, so let's hold off on implementing the change, but agree as to the form.

**Comment by durack1** [comment] 2017-01-18 01:46
From #51 and @taylor13 

table_id -- To enable QC checks be done on the frequency and realm attributes, I suggest we indicate the frequency and realm(s) that are included in each table in this CV. (For many tables, there will be a single frequency and single realm.) The syntax could be something like:

{
"table_id":{
"Amon":{
"frequency":["mon", "monClim"],
"realm":["atmos"]
},
"Omon":{
"frequency":["mon"],
"realm":["ocean"]
},
.
.
.

**Comment by durack1** [comment] 2017-01-18 01:47
From [#51](https://github.com/WCRP-CMIP/CMIP6_CVs/issues/51#issuecomment-250300992) and @durack1

@taylor13 following #52 (which is a duplicate and will be closed) I am appending the following information into this issue:
@taylor13 @dnadeau4 @martinjuckes we are awaiting these details to be finalised the following outputs, see http://clipc-services.ceda.ac.uk/dreq/index.html
for e.g. [table_id/miptable](http://clipc-services.ceda.ac.uk/dreq/index/miptable.html)

We are going to have to double check realm, and possibly others for consistency..

**Comment by taylor13** [comment] 2017-01-19 00:28
I think we should still wait a bit on adding this info. until after release of  the next version (or two?) of the data request.

**Comment by senesis** [comment] 2017-01-19 10:30
If we agree that some table can refer to multiple realms, this means that we need a check that no CMOR variable name refers to e.g the same variable but with different cell_methods

**Comment by taylor13** [comment] 2017-01-24 21:01
@senesis   To be sure, are you saying we should go through all of the CMOR tables and check that within each table all the variables have different CMOR names?    I think that is indeed essential (although in CMIP5 we sometimes included two variables with different "table entry" names, but with the same output names; groups chose one or the other depending on whether or not they were reporting a climatology vs. a full time series).  But what does "cell_methods" have to do with it?

**Comment by senesis** [comment] 2017-01-25 06:37
No, there is no problem with using the same 'CMOR name' (i.e. , in DR parlance, 'CMORvar label') for two distinct CMOR variables. The problem is when the CMOR name is the same while, from the scientist point of view (who has nothing to care about tables), the physical quantity is not computed in the same way (regardless of time averaging); this stronlgy correlated with the fact that output names should not be the same, and especially in the same realm. The best example is 'hfls' : it can be defined as the flux for the average over tiles of a mixed-tiles grid mesh (land + ocean) or for any of the tiles separatley, which should lead to use output names 'hfls', 'hflsa' and 'hflso', and not to rely on interpreting the table name and/or the realm and/or the cell_method attribute for distinguishing, and so to also use different CMOR names. 

----- Mail original -----

| De: "taylor13" <notifications@github.com>
| À: "WCRP-CMIP/CMIP6_CVs" <CMIP6_CVs@noreply.github.com>
| Cc: "Stéphane Sénési - work" <stephane.senesi@meteo.fr>, "Mention"
| <mention@noreply.github.com>
| Envoyé: Mardi 24 Janvier 2017 22:01:47
| Objet: Re: [WCRP-CMIP/CMIP6_CVs] table_id augment format with identifiers
| (#166)

| @senesis To be sure, are you saying we should go through all of the CMOR
| tables and check that within each table all the variables have different
| CMOR names? I think that is indeed essential (although in CMIP5 we sometimes
| included two variables with different "table entry" names, but with the same
| output names; groups chose one or the other depending on whether or not they
| were reporting a climatology vs. a full time series). But what does
| "cell_methods" have to do with it?

| —
| You are receiving this because you were mentioned.
| Reply to this email directly, view it on GitHub , or mute the thread .

-- 
----- Météo-France ----- 
SENESI STEPHANE 
CNRM/GMGEC/EST 
stephane.senesi@meteo.fr 
Fixe : +33 561079931

**Comment by taylor13** [comment] 2017-01-25 17:14
@senesis O.K. got it (and thanks for explaining that CMORvar label = CMOR name)
So, it's o.k. for a variable name to be the same for a quantity sampled at different frequencies (e.g., daily vs. monthly), but not one that samples different areas (e.g., land only vs. all surfaces).  Is that because you think users can more easily interpret the frequency from the table name than they can the realm?  [So I think scientists do probably care about the table name because it tells them what the sampling frequency is.]
In coming up with the naming scheme many years ago, I thought both the realm and frequency were easy to infer from the table name, and I thought a user should be able to find all datasets for a given physical quantity using the same CMOR name (no matter how it was sampled).  I still think this would be good, but if you can provide an example of how this is confusing, please do. 
Thanks for caring about these things.

**Comment by senesis** [comment] 2017-01-26 09:53
An example of confusion : LS3MIP asked for two variables useful for computing heat budget over land : dtes and hfls. While dtes in, by design a land variable, hfls is not, and there is not request in the DR for aversion of hfls with cell_method "where land". This means that any budget computed over a mixed mesh (ocean+land) will not be closed. One solution of course would be to add hfls in table Lmon with cell_method 'mean over land'; but this exemplifies how relying on too many pieces of context (table, realm) may lead to errors. My popsed solutin as been applied to the case of hfls on ice sheet, with name hflsIs, and extending this to the few other ambiguous variables (see previous thread) wouldn't be that heavy 

By the way : hflsIs is not used consistently across table: it is used in Limon but not in ImonAnt and ImonGre 

----- Mail original -----

| De: "taylor13" <notifications@github.com>
| À: "WCRP-CMIP/CMIP6_CVs" <CMIP6_CVs@noreply.github.com>
| Cc: "Stéphane Sénési - work" <stephane.senesi@meteo.fr>, "Mention"
| <mention@noreply.github.com>
| Envoyé: Mercredi 25 Janvier 2017 18:14:33
| Objet: Re: [WCRP-CMIP/CMIP6_CVs] table_id augment format with identifiers
| (#166)

| @senesis O.K. got it (and thanks for explaining that CMORvar label = CMOR
| name)
| So, it's o.k. for a variable name to be the same for a quantity sampled at
| different frequencies (e.g., daily vs. monthly), but not one that samples
| different areas (e.g., land only vs. all surfaces). Is that because you
| think users can more easily interpret the frequency from the table name than
| they can the realm? [So I think scientists do probably care about the table
| name because it tells them what the sampling frequency is.]
| In coming up with the naming scheme many years ago, I thought both the realm
| and frequency were easy to infer from the table name, and I thought a user
| should be able to find all datasets for a given physical quantity using the
| same CMOR name (no matter how it was sampled). I still think this would be
| good, but if you can provide an example of how this is confusing, please do.
| Thanks for caring about these things.

| —
| You are receiving this because you were mentioned.
| Reply to this email directly, view it on GitHub , or mute the thread .

-- 
----- Météo-France ----- 
SENESI STEPHANE 
CNRM/GMGEC/EST 
stephane.senesi@meteo.fr 
Fixe : +33 561079931

**Comment by taylor13** [comment] 2017-01-26 19:27
@senesis @martinjuckes   First, I've spotted some errors:
In table eday:
standard name for mrsol should be:  moisture_content_of_soil_layer
standard name for mrsll should be:   liquid_water_content_of_soil_layer
standard name for mrsfl should be:  frozen_water_content_of_soil_layer

Now back to the discussion:
I suspect LS3MIP made many mistakes in putting together their list of requested variables, and you are right, they won't be able to close their land budget for grid cells that are only partially land.  *IF* they want to consider the surface heat budget components, then besides dtes, they will need for the land portion of the grid cell only, the hfls, hfss, and the radiation components at the surface.   But maybe they're more interested in the heat content changes of the soil, in which case all they need is dtes.   Anyway, I lost the battle on how we could better group variables into tables, so I think we won't be able to do things absolutely uniformly.  If we find that the same CMOR variable name refers to the same variable but with different cell_methods, *and* those appear in the same table, then we need to correct it.  If we require different names for the the same variable, even when they appear in *different* tables, we'll have to make lots of changes, I think.  I think it's too late to do that.

**Comment by durack1** [comment] 2017-01-26 21:52
@taylor13 @senesis @martinjuckes I believe that this issue is more specific to the data request than to the CMIP6 CVs (this repo), so I wonder whether we should create a new `CMIP6_DataRequestIssues` or similar github repo, or whether @martinjuckes is catching these data request specific issues somewhere else.. I am sure we have problems with standard names in the OMIP request that I am yet to resolve.. Catching this all in one place is better than having it scattered around..

**Comment by senesis** [comment] 2017-01-27 08:11
@durack1  @taylor13 @martinjuckes I already wrote to Martin on a very close topic, who translated that in [ a  CMIP6_DataRequestIssues issue there](https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/68), (albeit some details are missing , which I will add shortly)

**Comment by taylor13** [comment] 2017-02-27 20:48
@durack1 @martinjuckes @dnadeau4  Martin confirms there is only one frequency associated with each table, but there can be multiple realms.  There may be some subsequent edits needed to the realms, but I think we can implement the following list into CMIP6:
'{"E1hr": "1hr", "Efx": "fx", "6hrLev": "6hr", "IfxAnt": "fx", "Oyr": "yr", "ImonGre": "mon", "CFday": "day", "Oday": "day", "EdayZ": "day", "LImon": "mon", "CFsubhr": "subhr", "Odec": "dec", "3hr": "3hr", "SImon": "mon", "CFmon": "mon", "Omon": "mon", "IyrGre": "yr", "IfxGre": "fx", "E6hrZ": "6hr", "Eday": "day", "E1hrClimMon": "1hrClimMon", "EmonZ": "mon", "Amon": "mon", "fx": "fx", "SIday": "day", "6hrPlev": "6hr", "AERhr": "hr", "AERmon": "mon", "E3hrPt": "3hr", "Esubhr": "subhr", "AERday": "day", "Oclim": "monClim", "Ofx": "fx", "AERfx": "fx", "6hrPlevPt": "6hr", "day": "day", "AERmonZ": "mon", "CF3hr": "3hr", "E3hr": "3hr", "CFsubhrOff": "subhr", "Emon": "mon", "ImonAnt": "mon", "Lmon": "mon", "IyrAnt": "yr", "Eyr": "yr"}'

'{"E1hr": ["atmos"], "Efx": ["", "atmos", "land", "landIce"], "IfxGre": ["land", "landIce"], "IfxAnt": ["land", "landIce"], "Oyr": ["ocean", "ocnBgchem"], "ImonGre": ["atmos", "land", "landIce", "landIce land"], "CFday": ["atmos"], "Oday": ["ocean", "ocnBgchem"], "EdayZ": ["atmos"], "LImon": ["land", "landIce", "landIce land"], "CFsubhr": ["atmos"], "Odec": ["ocean", "ocean seaIce"], "3hr": ["atmos", "land", "ocean"], "SImon": ["seaIce"], "CFmon": ["atmos"], "Omon": ["ocean", "ocean seaIce", "ocnBgchem"], "IyrGre": ["atmos", "land", "landIce", "landIce land"], "6hrLev": ["aerosol", "atmos"], "E6hrZ": ["atmos"], "day": ["atmos", "land", "landIce land", "ocean"], "E1hrClimMon": ["atmos"], "EmonZ": ["aerosol", "atmos"], "Amon": ["atmos", "atmos atmosChem"], "fx": ["atmos", "atmos land", "land", "ocean"], "SIday": ["seaIce"], "6hrPlev": ["aerosol", "atmos"], "AERhr": ["aerosol"], "AERmon": ["aerosol"], "E3hrPt": ["atmos"], "Esubhr": ["aerosol", "atmos"], "AERday": ["aerosol"], "Oclim": ["ocean"], "Ofx": ["ocean"], "AERfx": ["aerosol"], "6hrPlevPt": ["aerosol", "atmos", "land", "landIce land"], "Eday": ["", "aerosol", "atmos", "land", "landIce", "landIce land", "ocean"], "AERmonZ": ["aerosol"], "CF3hr": ["atmos"], "E3hr": ["", "atmos", "land"], "CFsubhrOff": ["atmos"], "Emon": ["", "aerosol", "atmos", "land", "ocean", "ocnBgchem"], "ImonAnt": ["atmos", "land", "landIce", "landIce land"], "Lmon": ["land", "land landIce"], "IyrAnt": ["atmos", "land", "landIce", "landIce land"], "Eyr": ["", "land", "ocean"]}'

The above list  (two json objects) were made with script attached below, and then using json.dumps on fr.freqDict and fr.realmDict. I think there are still some issues with the realm settings of some variables, so please let me know if you see something unexpected.
[fr_py.txt](https://github.com/WCRP-CMIP/CMIP6_CVs/files/804946/fr_py.txt)

**Comment by taylor13** [comment] 2017-02-27 21:18
Didn't mean to close this.

**Comment by taylor13** [comment] 2017-03-17 16:47
@durack1 Do you want me to implement this manually, or do you want to set up some automated system using the python script above?

**Comment by durack1** [comment] 2017-03-17 17:05
@taylor13 I think this needs to be automated, to prevent problems. We'll need to ascertain a way that these fields can be generated each time the script runs, so that we have consistent information with the up-to-date data request. Determining how the above was generated is the first step. @martinjuckes can you provide some insights here?

**Comment by durack1** [comment] 2017-03-22 17:59
@martinjuckes what is the best way for me to ensure that I have the latest version of the `table-id` information above? Is cloning the subversion `dreqPy` repository and interrogating that going to yield the most up-to-date information?

**Comment by durack1** [comment] 2017-03-22 18:05
@martinjuckes what is the best way for me to ensure that I have the latest version of the `table-id` information above? Is cloning the subversion `dreqPy` repository and interrogating that going to yield the most up-to-date information? I note that you have a pypi package https://pypi.python.org/pypi/dreqPy/01.beta.05 also available, however I am wondering if this is up-to-date with the latest?
Would it be more appropriate to clone your latest, http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/?

@taylor13 @dnadeau4 pinging you in case you have better suggestions

**Comment by martinjuckes** [comment] 2017-04-11 11:45
@durack1 just catching up on this. The pypi repository is up to date: go to https://pypi.python.org/pypi/dreqPy for the latest.  Where did you pick up the reference to 01.beta.05 ... that is an ancient version. 

On the variable naming: while there are patterns, there are few rules. The various MIPs ahve established their own patterns. The CF standard names are standardised, where they exist. This is a long process and we can't repeat that level of standardisation for the variable names. The assigment of `modeling_realm` also lacks a clear definition: it is only there to provide a clue. It would be good to have some clear patterns here .. but they really need to be established near the start of the process, not near the end.

**Comment by durack1** [comment] 2017-04-14 01:39
@martinjuckes thanks for clarifying the latest sources.. I'll make sure to pull down the latest version from pypi.. The `01.beta.05` ref was located on the page that I found doing a google search, so not sure why it pointed me to an older version..

If I see any other glaring inconsistencies with the CVs at [WCRP-CMIP/CMIP6_CVs](https://github.com/WCRP-CMIP/CMIP6_CVs) I'll raise a ticket either in this repo, or this and the [cmip6dr/CMIP6_DataRequest_VariableDefinitions](https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions) repo and link them

Thanks!

**Comment by durack1** [comment] 2017-04-21 18:12
@martinjuckes the current [`pypi dreqPy` version appears to still be `01.00.06`](https://pypi.python.org/pypi/dreqPy), is this updated when the `dreq` is incremented or is there a lag in its release?

**Comment by martinjuckes** [comment] 2017-05-05 16:15
@durack1 There is a lag, from a few hours to days, between updates of the web site, the CoG site and the pypi repository .. though I try to keep it down to a few hours.

**Comment by taylor13** [comment] 2017-05-23 22:26
Note: further discussion about multiple frequencies in a single table can be found at:
https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/147#issuecomment-291803000
and 
https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/166

**Comment by durack1** [comment] 2017-08-30 23:53
Update following the latest `01.00.15` Tables release in https://github.com/PCMDI/cmip6-cmor-tables/tree/master/Tables

**Comment by durack1** [comment] 2018-07-27 01:45
@taylor13 this current [CMIP6_table_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_table_id.json) is accurate with the latest [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/tree/master/Tables). The only entries that are not included are `coordinate`, `formula_terms` and `grids`.

If we have no intention of providing table descriptions e.g. `Omon: ocean realm monthly table`, then I think we can close this

**Comment by taylor13** [comment] 2018-07-27 14:50
I agree.  "coordinate", formula_terms, and "grid" are not part of the controlled vocab. because they are not used in creating file names and directories or in any way other than as input to CMOR.  Not sure I have permission to close, but I'll try.

**Closed by taylor13** 2018-07-27 14:50 UTC
Labels: question
