### ISSUE TITLE
'historical' initialized from 'past1000'

### ISSUE THREAD

**Issue by tyskosir** [WCRP-CMIP/CMIP6_CVs#957] opened 2020-08-20 05:55 UTC
As indicated in Table 1 of the PMIP4 past1000 description paper (https://doi.org/10.5194/gmd-10-4005-2017), a 'historical' simulation initialized from the end state of a 'past1000' simulation in 1850 is requested. However, only 'piControl' is defined as the parent experiment of 'historical' in CMIP6_experiment_id.json. The 'past1000' is not allowed as the parent experiment of 'historical'.

**Comment by durack1** [comment] 2020-08-20 13:36
@tyskosir thanks for raising this. @jypeter can you chime in here?

**Comment by matthew-mizielinski** [comment] 2020-08-20 17:01
@durack1, just a quick thought; Might be worth checking with the CMIP panel too on this one. The historical is one of the most published experiments and without a clear way of identifying the parentage of a given simulation via ESGF it will be tricky to distinguish between those simulations initialised from the piControl  and the  past1000  experiments (and past2k, see table 1 in the PMIP4 GMD paper).

**Comment by taylor13** [comment] 2020-08-20 17:27
@matthew-mizielinski @jypeter @durack1 .  Thanks, Matt, for thinking of that.  It does seem like this is a real problem that no one noticed until now.   Although these are all historical runs, so the experiment name is appropriate, many investigators will want to limit their analysis to a subset initialized in a particular way.    I'm at a loss how we might fix this problem.  @jpeter do you know how many historical runs have been published that were initialized from the past1000 or past2k simulations? If any have, then they must have incorrectly set parent_experiment_id to piControl, assuming PrePARE checks that parent_experiment_id is consistent with experiment_id, as specified in the CV.

**Comment by taylor13** [comment] 2020-08-20 18:02
reviewing briefly the GMD article, I now recall that the idea was these runs would be distinguished by assigning a different "i" value in the "ripf" identifier.  So, for example, if the historical run initialized from the piControl were assigned initialization_index=1, then runs initialized from past1000 or past2k would be assigned different initialization_indexes. Ideally, the meaning of each index in the "ripf" is defined in ES-DOC, and a user could consult ES-DOC before downloading data to obtain only the historical runs of interest.  That's  a lot of work and clearly not ideal.  
If this is how it's going to work, we will need to list all 3 parent experiments in the parent_experiment_id CV.  There are already a handful of experiments that have two options for parent_experiment_id, but we should probably check that CMOR and PrePARE are handling this rare case correctly.

**Comment by taylor13** [comment] 2020-08-20 20:06
Tsuyoshi (@tyskosir ; cc @jypeter)  Thanks again for raising this issue.   Can you answer either of the following?  (no need to investigate; just wondering if you know off the top of your head):

1. Have you already prepared your output files from this experiment for publication?  (Don't worry; you shouldn't have to alter them if you have.)
2. Do you know of any PMIP participants who have published output from historical runs initialized from either past1000 or past2k simulations?

thanks,
Karl

**Comment by tyskosir** [comment] 2020-08-21 02:50
@taylor13 (cc: @jypeter) Thanks Karl,

1. No, I was just testing it. I'm preparing to submit the historical output initialized from past1000 to ESGF, because we received a request from a researcher at another institution.

2. I don't have solid information unfortunately, but looking at the ESGF CMIP6 data holding list (https://pcmdi.llnl.gov/CMIP6/ArchiveStatistics/esgf_data_holdings/PMIP/index.html), MIROC-ES2L and EC-Earth3-Veg-LR (and our model, MRI-ESM2-0) have published the past1000 output; only the two models might have that possibility. Likewise, no model has published the past2k output, so the historical output initialized from past2k doesn't seem to have been published.

**Comment by taylor13** [comment] 2020-08-21 04:27
@tyskosir thanks for your help looking into this. Why don't you hold off a few days before generating a lot of output files.  Hopefully @jypeter will provide some input and then we should be able to make it possible to correctly write and publish the data.
Karl

**Comment by tyskosir** [comment] 2020-08-21 06:43
@taylor13 (cc @jypeter) OK, I'll do that. Many thanks.

**Comment by durack1** [comment] 2020-09-25 04:50
@jypeter we were hoping you could chime in on this, as it will impact PMIP experiments going forward

**Comment by tyskosir** [comment] 2020-10-02 01:01
@taylor13 Should I wait for the release of a new CMIP6_experiment_id.json for specifying past1000 as the parent experiment of historical, or cmorize the historical outputs with parent_experiment_id=piControl and i=1000 at this time?

**Comment by taylor13** [comment] 2020-10-02 04:19
I'll ping Jean-Yves (@jypeter) and hopefully get back to you shortly.

**Comment by taylor13** [comment] 2020-10-08 23:59
Hi @jypeter,
I understand that the email service at IPSL has been down for about a month, so perhaps you haven't gotten these messages, so I'm pinging you again (I'll also email you with further information and background).

**Comment by taylor13** [comment] 2020-10-22 00:47
I have sent the following email:
------------------------------------------------------
I still have not heard from Jean-Yves (hope he is o.k.), but I think we should wait no longer.  Let’s proceed as suggested earlier:
 
The issue is how to distinguish historical experiments branched from piControl from those branched from past1000 and past2k experiments.  The minimum requirement is to assign  a different i_index in the “ripf” variant identifier for runs initialized from different parents.  The recommendation for PMIP is:
For a historical simulation whose parent is past1000, set i_index=1000
For a historical simulation whose parent is past2k, set i_index=2000.
For historical simulations whose parent is the piControl, set i_index=1 (except in the unlikely case that 1 has already been used for a historical run initialized from a different parent).
 
This, we hope, will make it quite clear in the filenames that these are “unusual” historical runs.
 
Thanks for your patience in this matter.
 
Best regards,
Karl

**Comment by tyskosir** [comment] 2020-10-26 02:11
@taylor13 Noted with thanks. I'll start cmorizing the data.

**Comment by tyskosir** [comment] 2020-10-29 23:55
We have published the historical r1i1000p1f1 data with MRI-ESM2-0 on ESGF. Many thanks.

**Comment by taylor13** [comment] 2020-10-30 16:08
Excellent!  There's no changing our minds now!  
I'll close this issue.

**Comment by jypeter** [comment] 2020-12-09 20:16
Thank you @taylor13 @durack1 @matthew-mizielinski  and @tyskosir for the discussion and the `i1000` and `i2000` suggestions! My apologies for not handling this issue much earlier

I have sent an official mail about this standard `variant_label` to the PMIP4 participating groups

Unfortunately, while reviewing mails, etc, I have found 2 loose ends. I hope @taylor13 can re-open this issue and we can easily (and more quickly this time) sort this out

### Which activity_id should be used?

Under which ESGF `activity_id` should these _historical_ experiments be published?

"CMIP", because "historical" is defined in CMIP, or "PMIP"? The MRI experiment has been created with the "CMIP" activity.

As Karl suggested in one of his early mails, having these experiments in "PMIP" would make it easier for people to search them on ESGF, and would also prevent people looking only for "CMIP" and "historical from piControl" from getting them. 

But now that we have the MRI experiment in CMIP, maybe it's better to put everything in CMIP. Unless @tyskosir can reprocess and republish the files

### Which "parent_experiment_id"/"parent_activity_id" should be used?

I have checked the current definition of the `historical` experiment in the CV. Currently, only the "piControl"/"CMIP" values can be used for the "parent_experiment_id"/"parent_activity_id" metadata

In our case (continuation of past1000 or past2k) it should probably be:

- `parent_experiment_id`: "past1000" or "past2k"
- ` parent_activity_id`: "PMIP"

### The solution used by MRI

I have copied below some metadata from one of the published MRI files. @tyskosir has cleverly used the `branch_method` keyword to describe/solve the problem. We could ask the other PMIP groups to do the same.

There are many PMIP groups, but not that many with past1000 experiments (probably even less that will be able to handle past2k). And I don't know how many will run continuation historical experiments

```
    :activity_id = "CMIP" ;
    :branch_method = "standard (the actual parent run: PMIP past1000)" ;
    :experiment_id = "historical" ;
    :parent_activity_id = "CMIP" ;
    :parent_experiment_id = "piControl" ;
    :variant_label = "r1i1000p1f1" ; 
```

**Comment by taylor13** [comment] 2020-12-09 22:12
@jypeter :  The historical experiments are indeed CMIP activity sponsored, so it's appropriate (and won't break things or make published data inconsistent) to set activity_id = "CMIP" for these.

I had forgotten about the issue of parent_experiment although it was discussed above.  I had suggested that if CMOR, ES-DOCs, and the data citation/PID services can handle it (or be easily modified to handle it), we should list in the CV all three options for parents of the historical runs: piControl, past1000, and past2k.  Modeling groups would then be able to identify the parent correctly.  The fact that @tyskosir skirted this issue by setting experiment_id=piControl should not be cause for concern (or require rewriting).  I don't think any of the automated processing in place for CMIP6 actually uses this information.  An errata could be registered for the affected MRI files indicating that the true parent is past1000, and the parent_experiment_id was simply misidentified in the file metadata. 

@mauzy1 https://github.com/MartinaSt @hassell could you please check and see whether CMOR could handle

**Comment by mauzey1** [comment] 2020-12-11 23:38
@taylor13 I don't think there is an issue with CMOR with the historical experiment having piControl, past1000, and past2k as parent experiments.

**Comment by durack1** [comment] 2020-12-11 23:39
@mauzey1 did we want to do any testing on that, or should I just make the update?

**Comment by durack1** [comment] 2020-12-11 23:43
@taylor13 to catch all cases, we'd need to make the following amendment to the [`historical`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L4543-L4571) experiment:

```python
parent_activity_id = CMIP -> CMIP, PMIP
parent_experiment_id = piControl -> piControl, past1000, past2k
```
@mauzey1 would this update cause problems?

**Comment by mauzey1** [comment] 2020-12-11 23:58
I applied those changes to CMIP6_CV.json and tried running PrePARE on a `historical` experiment dataset.  It didn't have any errors.  I also ran the CMOR test suite with the changes and it passed all tests.

There are other experiments that have multiple parent experiments, such as [`esm-1pct-brch-1000PgC`](https://github.com/PCMDI/cmip6-cmor-tables/blob/1746d197789cdbde5d36e3715e65a9f9506bd100/Tables/CMIP6_CV.json#L4729-L4746).

**Comment by tyskosir** [comment] 2020-12-12 00:20
@jypeter @taylor13 @mauzey1 @durack1 Thank you for your follow-up regarding this issue.

**Comment by taylor13** [comment] 2020-12-12 03:49
thanks very much @mauzey1.  Let's not proceed further until we hear from folks regarding impact on the other components of the infrastructure.  It will be o.k. (but, of course, not really correct) to identify the parent of these experiments as piControl since we don't expect this will impact things terribly.

**Comment by durack1** [comment] 2020-12-15 19:13
We can proceed with the changes described above https://github.com/WCRP-CMIP/CMIP6_CVs/issues/957#issuecomment-743484010.

A number of simulations have already been published with incorrect metadata (from 2 institutions @taylor13?) so we will need to get errata raised against these non-conforming simulations, so that erroneous metadata is identified.

The changes above will be merged later today

**Closed** 2020-12-15 20:28 UTC
