### ISSUE TITLE
Versioning of CMIP6_CVs

### ISSUE THREAD

**Issue by matthew-mizielinski** [WCRP-CMIP/CMIP6_CVs#333] opened 2017-05-30 11:21 UTC
I note that the releases of the CVs in this repository are explicitly linked to CMOR versions, would it be possible to (also) tag releases against the versions in the CMIP6 global attributes documentation, currently at 6.2.3?

Given that many of the changes over recent months are associated with adding information (e.g. `institute_id`s), rather than changing the structure of the CVs, perhaps an additional level of version numbering, i.e. 6.2.3.x, could be added and x incremented every so often (not necessarily after every change).

**Comment by taylor13** [comment] 2017-05-30 16:12
yes, please contribute to the discussion at https://github.com/WCRP-CMIP/CMIP6_CVs/issues/28
thanks,
Karl

**Comment by durack1** [comment] 2017-05-31 15:00
@matthew-mizielinski this is a dupe of #28, so will close this and we can direct comments into the open issue

**Closed by durack1** 2017-05-31 15:00 UTC
