### ISSUE TITLE
source_id registration of CMCC-ESM2-SR5

### ISSUE THREAD

**Issue by escoccimarro** [WCRP-CMIP/CMIP6_CVs#296] opened 2017-04-19 09:26 UTC
activity_participation = [CMIP,C4MIP, LS3MIP, LUMIP]
aerosol = MAM3
atmosphere = CAM5.3 (1deg 288x192 longitude/latitude, 30 levels, top at ~2hPa)    
atmospheric_chemistry = None
institution_id = CMCC
label = CMCC-ESM2-SR5
label_extended = CMCC-ESM2-SR5 
land_ice = None
land_surface = CLM4.5 (BGC mode)
nominal_resolution_atmos = 100 km
nominal_resolution_landIce = None 
nominal_resolution_ocean = 100 km
nominal_resolution_aerosol = 100 km
nominal_resolution_atmosChem = None
nominal_resolution_land = 100 km
nominal_resolution_ocnBgchem = 100 km
nominal_resolution_seaIce = 100 km
ocean = NEMO3.6 (ORCA1 tripolar primarly 1 deg lat/lon with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 50 vertical levels; top grid cell 0.5 m)     
ocean_biogeochemistry = BFM5.1
release_year = 2017
sea_ice = CICE4.0
source_id = CMCC-ESM2-SR5

**Comment by durack1** [comment] 2017-04-19 16:54
@escoccimarro thanks for this, we need a couple of extra pieces of information and a couple of clarifications which I have guessed at (between the `###` entries) below:
```
atmosphere = CAM5.3 (1deg; ###288x192 longitude/latitude###; 30 levels; top at ~2 hPa)
ocean = NEMO3.6 (ORCA1 tripolar primarly 1 deg lat/lon with meridional refinement down to 1/3 degree in the tropics; ###360 x 180 longitude/latitude;### 50 vertical levels; top grid cell 0.5 m)
nominal_resolution_aerosol = 100 km
nominal_resolution_atmosChem = None
nominal_resolution_land = 100 km
nominal_resolution_ocnBgchem = 100 km
nominal_resolution_seaIce = 100 km
```

**Comment by escoccimarro** [comment] 2017-04-20 08:58
we updated the information as required.
thanks

**Comment by durack1** [comment] 2017-04-22 02:34
@escoccimarro thanks for this, peek at [CMIP6_source_id.html](http://rawgit.com/WCRP-CMIP/CMIP6_CVs/master/src/CMIP6_source_id.html) and let me know if any further tweaks are required

**Comment by durack1** [comment] 2022-05-17 19:52
@escoccimarro @tomaslovato it appears that we have datasets published for the `CMCC-ESM2-SR5` model for the LS3MIP and LUMIP activities, however, these are not available through [ESGF](https://esgf-node.llnl.gov/search/cmip6/?source_id=CMCC-ESM2-SR5), were they retracted? The model appears to have been unregistered, somewhat erroneously as it doesn't appear in the [CMIP6_source_id.html](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_source_id.html) page.

Can you please confirm the details above are correct (in particular, whether this model will contribute to CMIP and C4MIP), and once I have these confirmed I will re-register, or please clarify if the datasets that we have should be purged, as it is an invalid contribution

**Comment by tomaslovato** [comment] 2022-05-18 08:55
@durack1 the datasets related to `CMCC-ESM2-SR5` were unfortunately published before the update of the CVs table with the reordering of CMCC model participating to CMIP6 (as discussed in #846). In more detail, changes were made in https://github.com/WCRP-CMIP/CMIP6_CVs/commit/4705e28124103773c0ca23f68cfc56663020f888 and https://github.com/WCRP-CMIP/CMIP6_CVs/commit/d6660d7c814c5d0ace2c883bf32c7123bb0e3dc3.


> @escoccimarro @tomaslovato it appears that we have datasets published for the CMCC-ESM2-SR5 model for the LS3MIP and LUMIP activities, however, these are not available through [ESGF](https://esgf-node.llnl.gov/search/cmip6/?source_id=CMCC-ESM2-SR5), were they retracted?

At that time, based on the indication from @MartinaSt we had to retract the data published under `CMCC-ESM2-SR5`  and republish them under `CMCC-ESM2` (she also reported this known issue in #900), as the renaming was not allowed under ESGF due to the version tracking of data.

I confirm that `CMCC-ESM2-SR5` was correctly unregistered and you can purge the related datasets from your server.

I hope this will help!

**Comment by durack1** [comment] 2022-05-18 17:27
@tomaslovato thanks for clarifying, we'll clean up our local (LLNL/PCMDI) holdings so that these files are deleted. I note that [`CMCC-ESM2` also includes data for `LS3MIP` and `LUMIP`](https://esgf-node.llnl.gov/search/cmip6/?source_id=CMCC-ESM2), so I assume the valid (correctly named) datasets are currently available, and deleting the erroneous data is the correct path.

@sashakames @mauzey1 @taylor13 ping! (Will close this issue when we have resolved the local erroneous data issue)

**Comment by durack1** [comment] 2022-06-08 03:26
@sashakames, @mauzey1 can we schedule a time to chat about the discussion above https://github.com/WCRP-CMIP/CMIP6_CVs/issues/296#issuecomment-1130289604

**Comment by sashakames** [comment] 2022-06-08 14:04
@durack1 Open to chatting about this.  Looks like all data is retracted from the index already as I don't see the source_id in the search results.

**Comment by durack1** [comment] 2022-06-09 04:34
@sashakames @mauzey1 @taylor13 action today has resolved the ESGF-LLNL inconsistency, so will close

**Closed by durack1** 2022-06-09 04:34 UTC
Labels: Awaiting info
