### ISSUE TITLE
table_id missing or wrong

### ISSUE THREAD

**Issue by dnadeau4** [WCRP-CMIP/CMIP6_CVs#132] opened 2016-11-08 22:25 UTC
Please replace or add `"day"` in your list for CMOR.    
https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_table_id.json#L7

**Comment by durack1** [comment] 2016-11-08 22:52
@dnadeau4 this is a duplicate of #128 - resolving #128 will also solve this. Is it holding up your progress with `CMOR 3.2.x`?

@taylor13 will likely need your input here

**Comment by durack1** [comment] 2016-11-08 23:50
Closing this as a duplicate of #128 - @dnadeau4 please response to the open question in #128 and we should be able to get a short term workaround until the `table_id` values are finalised

**Closed by durack1** 2016-11-08 23:50 UTC
Labels: duplicate, help wanted
