### ISSUE TITLE
Add new activity to Source_id EC-Earth3 

### ISSUE THREAD

**Issue by shutingdk** [WCRP-CMIP/CMIP6_CVs#748] opened 2019-07-29 14:48 UTC
Here are instructions both for registering your institution and model for CMIP6 and for raising other issues concerning CMIP6 controlled vocabularies. We can update details iteratively, until you begin writing CMIP6 data.

PLEASE DELETE THESE INSTRUCTIONS BEFORE SUBMITTING YOUR REGISTRATION/ISSUE

*********************************************
## Registering your institution and model
*********************************************
Before publishing CMIP6 model output on ESGF, you must register information about your institution and  model as described in the registration guidance documents available at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Institution_registration_template.md and https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Model_registration_template.md. 

*********************************************
## Raising other issues
*********************************************
Your issue "title" should begin with the name of the Controlled Vocabulary of interest and also include a terse indication of the issue (e.g., "activity_id -- add 'PMIP'").

**Comment by durack1** [comment] 2019-07-29 15:24
@shutingdk there is no content above, rather the template remains. Please edit to indicate what you want amended

**Comment by durack1** [comment] 2019-07-29 15:25
@shutingdk I believe this an incomplete duplicate of #749, so will close this

**Closed by durack1** 2019-07-29 15:25 UTC
