### ISSUE TITLE
CMIP6 PMIP past2k overlap with past1000

### ISSUE THREAD

**Issue by charliepascoe** [WCRP-CMIP/CMIP6_CVs#979] opened 2020-10-27 12:05 UTC
The PMIP past2k experiment runs from 0 to 1850, but from 850 to 1850 past2k has the same forcings as the past1000 experiment. 

Back in May KT wrote:

"It seems to me if the second half of the past2k experiment is forced with the same forcing as the past1000 experiment, then in the data archive, the 2nd half should be stored with experiment_id="past1000" and its parent_experiment_id="past2k". Of course those running only the past1000 experiment would have experiment_id="past1000" and its parent_experiment_id="no parent" (according to the current CV).

So the metadata would indicate that different initialization procedures were used for different past1000 experiments, but I think most users would just like to get all the simulations of the past1000, and not have to get some of them by downloading a part of past2k experiment.

Of course other folks interested only in the runs covering the full 2k period would then have to download the past2k data plus the past1000 data for those models who had run the full 2000 years.

Thoughts?"

See also https://github.com/ES-DOC/esdoc-project/issues/83

**Comment by durack1** [comment] 2020-10-28 19:14
@charliepascoe this is likely a dupe of #957, did you want to copy the above into that issue and close this one?

**Comment by durack1** [comment] 2020-11-16 19:39
@charliepascoe did you see the note above?

**Comment by durack1** [comment] 2020-12-05 01:02
@taylor13 did you want to chime in here, it seems @charliepascoe wants something done, but it is not clear to me what

**Comment by taylor13** [comment] 2020-12-06 17:15
@charliepascoe and @durack1:  This is different from issue https://github.com/WCRP-CMIP/CMIP6_CVs/issues/957 , and I don't think we ever really resolved this.  To decide what to recommend, we could examine the output reported from the past1000 and past2k experiments.  If those publishing past2k runs have split the output and stored the first 1000 years under experiment_id="past2k" and the second 1000 years under "past1000", then we should recommend that.  If those publishing past2k runs have store all 2000 years under experiment_id="past2k", then we should recommend that.

**Comment by matthew-mizielinski** [comment] 2020-12-15 21:00
Hi all, I note here that the past1000 is a tier 1 PMIP experiment running from 850 to 1849, while the past2k is a tier 3 experiment (no data published as yet) running from year 1 to 1849. Both experiments have "no parents" as defined in the CVs so it would be a little complex to sustain both a "no parents" option and a parent_experiment_id="past2k" option to support this (I don't think we have such a case elsewhere in CMIP6)..

**Comment by durack1** [comment] 2020-12-15 21:38
A point that we haven't recognized, is that with different initialization, the phases of (internal) variability will likely be different (just like single experiment ensemble members) and therefore, there may be a way to consider both experiments during their overlap period as ensemble members, BUT, this assumes that the 850 years of non-overlap forcing hasn't set up the model response to be very different. As such, I don't think there is anything for us to do here. Not sure if there are other compelling arguments, if not, we'll close this issue

**Comment by durack1** [comment] 2021-01-15 22:44
@taylor13 @matthew-mizielinski @charliepascoe I do not believe there is anything to do here, so if I don't hear otherwise will close this issue next week

**Closed** 2021-01-19 23:37 UTC
Labels: question
