### ISSUE TITLE
experiment_id: Definitions of 1pctCO2-rad and 1pctCO2-bgc

### ISSUE THREAD

**Issue by martinjuckes** [WCRP-CMIP/CMIP6_CVs#328] opened 2017-05-23 14:08 UTC
The experiment 1pctCO2-rad currently has the definitiion "Radiatively-coupled specified concentration simulation in which CO2 increases at a rate of 1% per year until quadrupling", which is slightly misleading because the 1pctCO2 experiment also has radiatively coupled CO2. The distinctive feature in 1pctCO2-rad is that there are two CO2 concentrations in play, one involved in the carbon cycle and one linked to the radiation code. 1pctCO2-rad and 1pctCO2-bgc form a pair: in the first the radiatively coupled CO2 is increasing, while the carbon cycle CO2 remains at control levels; in the 2nd this is reversed. After discussion with Chris Jones, I suggest the following descriptions (designed to make sense when read in isolation):
1pctCO2-rad: "1 percent per year increasing CO2 coupled to the radiation code with control CO2 concentrations applied in the carbon cycle",
1pctCO2-bgc: "1 percent per year increasing CO2 coupled to the carbon-cycle code with control CO2 concentrations applied in the radiation".

**Comment by durack1** [comment] 2017-05-28 02:46
@taylor13 can we get clearance to make these changes from the MIP-chairs?

**Comment by durack1** [comment] 2017-06-14 18:49
@martinjuckes @taylor13 @charliepascoe this is a duplicate of #339 so will copy this across and close this issue

**Closed by durack1** 2017-06-14 18:49 UTC
